"""
Shared email transport and CloudCare notification templates.

The transport prefers Brevo's HTTP API, then falls back to Resend and SMTP so
local demos keep working with the existing environment variables. Template
builders own presentation only; callers decide when a notification is needed.
"""

from __future__ import annotations

import json
import smtplib
import urllib.error
import urllib.request
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from html import escape
from typing import Any


_BRAND = "#2F6690"
_TEXT = "#10222E"
_MUTED = "#627785"
_BORDER = "#E4EBE8"
_BG = "#F7FAF9"
_DANGER = "#B3261E"


def _sender_email(settings: Any) -> str:
    sender = getattr(settings, "smtp_from", "") or ""
    if not sender or "@smtp-brevo.com" in sender or "@" not in sender:
        return "teamalpha817@gmail.com"
    return sender


def _fmt_money(value: Any) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "$0.00"


def _fmt_pct(value: Any) -> str:
    try:
        return f"{float(value) * 100:.0f}%"
    except (TypeError, ValueError):
        return "0%"


def _text(value: Any, default: str = "-") -> str:
    if value is None or value == "":
        return default
    return escape(str(value))


def _provider_error(provider: str, detail: str) -> dict[str, str]:
    reason = detail
    if provider == "brevo" and "unrecognised IP address" in detail:
        reason = "BREVO_UNAUTHORIZED_IP"
    elif provider == "brevo" and "unauthorized" in detail.lower():
        reason = "BREVO_UNAUTHORIZED"
    elif provider == "smtp" and "Unauthorized IP address" in detail:
        reason = "SMTP_UNAUTHORIZED_IP"
    return {"provider": provider, "reason": reason, "detail": detail}


def _shell(title: str, preheader: str, body: str) -> str:
    return f"""<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{_text(title)}</title>
  </head>
  <body style="margin:0;background:{_BG};color:{_TEXT};font-family:Arial,Helvetica,sans-serif;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;">{_text(preheader)}</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:{_BG};padding:24px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:760px;background:#FFFFFF;border:1px solid {_BORDER};border-radius:8px;overflow:hidden;">
            <tr>
              <td style="background:{_TEXT};color:#FFFFFF;padding:22px 28px;">
                <div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#C9D8D2;">CloudCare AgentOps</div>
                <h1 style="margin:8px 0 0;font-size:24px;line-height:1.25;">{_text(title)}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:26px 28px;">{body}</td>
            </tr>
            <tr>
              <td style="border-top:1px solid {_BORDER};padding:16px 28px;color:{_MUTED};font-size:12px;">
                Generated by CloudCare. Keep this message for audit context; use the dashboard for rollback or approval actions.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>"""


def _metric_card(label: str, value: Any, color: str = _BRAND) -> str:
    return f"""
      <td style="width:25%;padding:6px;">
        <div style="border:1px solid {_BORDER};border-radius:8px;padding:14px;background:#FBFDFC;">
          <div style="font-size:12px;color:{_MUTED};">{_text(label)}</div>
          <div style="margin-top:6px;font-size:21px;font-weight:700;color:{color};">{_text(value)}</div>
        </div>
      </td>"""


def send_email_status_sync(to_email: str, subject: str, html: str, settings: Any) -> dict[str, Any]:
    """Best-effort send with a structured receipt for UI/audit feedback."""
    sender_email = _sender_email(settings)
    errors: list[dict[str, str]] = []

    if getattr(settings, "brevo_api_key", ""):
        try:
            req = urllib.request.Request(
                "https://api.brevo.com/v3/smtp/email",
                data=json.dumps(
                    {
                        "sender": {"email": sender_email, "name": "CloudCare"},
                        "to": [{"email": to_email}],
                        "subject": subject,
                        "htmlContent": html,
                    }
                ).encode("utf-8"),
                headers={
                    "api-key": settings.brevo_api_key,
                    "Content-Type": "application/json",
                    "Accept": "application/json",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as response:
                response.read()
                return {"sent": True, "provider": "brevo", "errors": []}
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8")
            print(f"[email] Brevo API error: {exc.code} - {detail}")
            errors.append(_provider_error("brevo", detail))
        except Exception as exc:  # noqa: BLE001 - email is best-effort
            print(f"[email] Brevo API error: {exc}")
            errors.append(_provider_error("brevo", str(exc)))

    if getattr(settings, "resend_api_key", ""):
        try:
            req = urllib.request.Request(
                "https://api.resend.com/emails",
                data=json.dumps(
                    {
                        "from": "CloudCare <onboarding@resend.dev>",
                        "to": to_email,
                        "subject": subject,
                        "html": html,
                    }
                ).encode("utf-8"),
                headers={
                    "Authorization": f"Bearer {settings.resend_api_key}",
                    "Content-Type": "application/json",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as response:
                response.read()
                return {"sent": True, "provider": "resend", "errors": errors}
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8")
            print(f"[email] Resend API error: {exc.code} - {detail}")
            errors.append(_provider_error("resend", detail))
        except Exception as exc:  # noqa: BLE001 - email is best-effort
            print(f"[email] Resend API error: {exc}")
            errors.append(_provider_error("resend", str(exc)))

    if getattr(settings, "smtp_username", "") and getattr(settings, "smtp_password", ""):
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = sender_email
            msg["To"] = to_email
            msg.attach(MIMEText(html, "html"))
            with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=10) as server:
                server.starttls()
                server.login(settings.smtp_username, settings.smtp_password)
                server.sendmail(msg["From"], [to_email], msg.as_string())
            return {"sent": True, "provider": "smtp", "errors": errors}
        except Exception as exc:  # noqa: BLE001 - email is best-effort
            print(f"[email] SMTP error: {exc}")
            errors.append(_provider_error("smtp", str(exc)))

    if not errors:
        errors.append(_provider_error("config", "No email provider is configured."))
    return {"sent": False, "provider": None, "errors": errors}


def send_email_sync(to_email: str, subject: str, html: str, settings: Any) -> bool:
    """Best-effort send: Brevo HTTP API -> Resend HTTP API -> raw SMTP."""
    return bool(send_email_status_sync(to_email, subject, html, settings)["sent"])


def build_approval_email_html(context: dict[str, Any]) -> str:
    body = f"""
      <p style="margin:0 0 16px;font-size:14px;color:{_MUTED};">A cost optimization proposal is waiting for human approval.</p>
      <p style="font-size:14px;"><strong>Resource:</strong> {_text(context.get('resource_name'))}</p>
      <p style="font-size:14px;"><strong>Proposed action:</strong> {_text(context.get('action_plain_english'))}</p>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:14px -6px;">
        <tr>
          {_metric_card("Estimated savings", _fmt_money(context.get('savings_monthly')) + "/mo")}
          {_metric_card("Confidence", _fmt_pct(context.get('confidence_score')))}
          {_metric_card("Risk", _fmt_pct(context.get('risk_score')), _DANGER)}
        </tr>
      </table>
      <div style="border-left:4px solid {_BRAND};padding:10px 14px;background:#F5F9F8;color:{_MUTED};font-size:13px;">
        {_text(context.get('rationale'))}
      </div>
      <div style="margin:24px 0;text-align:center;">
        <a href="{_text(context.get('approve_url'))}" style="display:inline-block;margin:0 8px 10px;padding:12px 28px;background:{_BRAND};color:#FFFFFF;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Approve</a>
        <a href="{_text(context.get('reject_url'))}" style="display:inline-block;margin:0 8px 10px;padding:12px 28px;background:#FFFFFF;color:{_DANGER};border:1.5px solid {_DANGER};text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Reject</a>
      </div>
      <p style="font-size:12px;color:{_MUTED};">This link expires in 24 hours and can only be used once.</p>
    """
    return _shell("Cost Optimization Awaiting Approval", "A CloudCare proposal needs your decision.", body)


def send_approval_email_sync(to_email: str, context: dict[str, Any], settings: Any) -> bool:
    subject = f"CloudCare - Approve: {context['action_plain_english']} on {context['resource_name']}"
    print(f"[Supervisor] Approval email to {to_email}: {subject}")
    return send_email_sync(to_email, subject, build_approval_email_html(context), settings)


def build_completion_email_html(context: dict[str, Any]) -> str:
    body = f"""
      <p style="margin:0 0 16px;font-size:14px;color:{_MUTED};">An approved CloudCare action finished execution.</p>
      <p style="font-size:14px;"><strong>Resource:</strong> {_text(context.get('resource_arn'))}</p>
      <p style="font-size:14px;"><strong>What changed:</strong> {_text(context.get('action_type'))} ({_text(context.get('status'))})</p>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:14px -6px;">
        <tr>
          {_metric_card("Predicted savings", _fmt_money(context.get('predicted_savings_monthly')) + "/mo")}
          {_metric_card("Execution status", context.get('status'))}
        </tr>
      </table>
      <div style="margin:24px 0;text-align:center;">
        <a href="{_text(context.get('rollback_link'))}" style="display:inline-block;padding:12px 28px;background:#FFFFFF;color:{_DANGER};border:1.5px solid {_DANGER};text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">View / Roll back in dashboard</a>
      </div>
      <p style="font-size:12px;color:{_MUTED};">Actual savings will be confirmed once the next billing cycle's FOCUS data lands.</p>
    """
    return _shell("Action Completed", "A CloudCare execution completed.", body)


def send_completion_email_sync(to_email: str, context: dict[str, Any], settings: Any) -> bool:
    subject = f"CloudCare - Completed: {context['action_type']} on {context['resource_arn']}"
    print(f"[Executor] Completion email to {to_email}: {subject}")
    return send_email_sync(to_email, subject, build_completion_email_html(context), settings)


def _agent_rows(steps: list[dict[str, Any]]) -> str:
    if not steps:
        return f"""<tr><td colspan="4" style="padding:12px;color:{_MUTED};">No agent step details were returned.</td></tr>"""
    rows = []
    for step in steps:
        metrics = ", ".join(f"{m.get('label')}: {m.get('value')}" for m in step.get("metrics") or [])
        rows.append(
            f"""
            <tr>
              <td style="padding:12px;border-top:1px solid {_BORDER};font-weight:700;">{_text(step.get('name'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_text(step.get('status'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};color:{_MUTED};">{_text(step.get('summary'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};color:{_MUTED};">{_text(metrics)}</td>
            </tr>"""
        )
    return "".join(rows)


def _proposal_rows(proposals: list[dict[str, Any]]) -> str:
    if not proposals:
        return f"""<tr><td colspan="5" style="padding:12px;color:{_MUTED};">No action proposals were produced in this run.</td></tr>"""
    rows = []
    for proposal in proposals[:10]:
        rows.append(
            f"""
            <tr>
              <td style="padding:12px;border-top:1px solid {_BORDER};font-weight:700;">{_text(proposal.get('action_type'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_text(proposal.get('status'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_fmt_money(proposal.get('expected_monthly_savings'))}/mo</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_text(proposal.get('risk_level'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};color:{_MUTED};">{_text(proposal.get('rationale_plain_english') or proposal.get('rationale') or proposal.get('resource_arn'))}</td>
            </tr>"""
        )
    return "".join(rows)


def _execution_rows(executions: list[dict[str, Any]]) -> str:
    if not executions:
        return f"""<tr><td colspan="4" style="padding:12px;color:{_MUTED};">No executions were linked to this command yet.</td></tr>"""
    rows = []
    for execution in executions[:10]:
        rows.append(
            f"""
            <tr>
              <td style="padding:12px;border-top:1px solid {_BORDER};font-weight:700;">{_text(execution.get('action_type'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_text(execution.get('status'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};">{_text(execution.get('execution_mode'))}</td>
              <td style="padding:12px;border-top:1px solid {_BORDER};color:{_MUTED};">{_text(', '.join(execution.get('reason_codes') or []))}</td>
            </tr>"""
        )
    return "".join(rows)


def build_agent_command_analysis_email_html(context: dict[str, Any]) -> str:
    summary = context.get("summary") or {}
    status = str(context.get("status") or "unknown")
    status_color = _BRAND if status == "success" else _DANGER
    warning = ""
    if context.get("persistence_error"):
        warning = f"""
          <div style="border:1px solid #F0C6C3;background:#FFF7F6;color:{_DANGER};border-radius:8px;padding:12px;margin:18px 0;font-size:13px;">
            <strong>Degraded run:</strong> {_text(context.get('persistence_error'))}
          </div>"""

    body = f"""
      <p style="margin:0 0 16px;font-size:14px;color:{_MUTED};">
        Agent command {_text(context.get('run_id'))} finished for {_text(context.get('provider'))}
        account {_text(context.get('account_id'))} in {_text(context.get('region'))}.
      </p>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:14px -6px;">
        <tr>
          {_metric_card("Status", status, status_color)}
          {_metric_card("Resources", summary.get('resources', 0))}
          {_metric_card("Findings", summary.get('findings', 0))}
          {_metric_card("Potential/mo", _fmt_money(summary.get('potential_monthly_savings')))}
        </tr>
        <tr>
          {_metric_card("Proposals", summary.get('proposals', 0))}
          {_metric_card("Pending", summary.get('pending_approvals', 0))}
          {_metric_card("Blocked", summary.get('blocked', 0), _DANGER)}
          {_metric_card("Executed", summary.get('executed_or_simulated', 0))}
        </tr>
      </table>
      {warning}
      <h2 style="font-size:17px;margin:24px 0 8px;">Agent Analysis</h2>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid {_BORDER};border-radius:8px;border-collapse:separate;border-spacing:0;overflow:hidden;font-size:13px;">
        <tr style="background:#F5F9F8;color:{_MUTED};">
          <th align="left" style="padding:12px;">Agent</th>
          <th align="left" style="padding:12px;">Status</th>
          <th align="left" style="padding:12px;">What happened</th>
          <th align="left" style="padding:12px;">Evidence</th>
        </tr>
        {_agent_rows(context.get('steps') or [])}
      </table>
      <h2 style="font-size:17px;margin:24px 0 8px;">Decisions</h2>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid {_BORDER};border-radius:8px;border-collapse:separate;border-spacing:0;overflow:hidden;font-size:13px;">
        <tr style="background:#F5F9F8;color:{_MUTED};">
          <th align="left" style="padding:12px;">Action</th>
          <th align="left" style="padding:12px;">Status</th>
          <th align="left" style="padding:12px;">Savings</th>
          <th align="left" style="padding:12px;">Risk</th>
          <th align="left" style="padding:12px;">Rationale</th>
        </tr>
        {_proposal_rows(context.get('proposals') or [])}
      </table>
      <h2 style="font-size:17px;margin:24px 0 8px;">Execution Audit</h2>
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid {_BORDER};border-radius:8px;border-collapse:separate;border-spacing:0;overflow:hidden;font-size:13px;">
        <tr style="background:#F5F9F8;color:{_MUTED};">
          <th align="left" style="padding:12px;">Action</th>
          <th align="left" style="padding:12px;">Status</th>
          <th align="left" style="padding:12px;">Mode</th>
          <th align="left" style="padding:12px;">Reason codes</th>
        </tr>
        {_execution_rows(context.get('executions') or [])}
      </table>
      <div style="margin:24px 0;text-align:center;">
        <a href="{_text(context.get('dashboard_url'))}" style="display:inline-block;padding:12px 28px;background:{_BRAND};color:#FFFFFF;text-decoration:none;border-radius:6px;font-weight:700;font-size:14px;">Open Agent Command Center</a>
      </div>
    """
    return _shell("Agent Command Analysis Complete", "CloudCare completed a real-time agent command analysis.", body)


def send_agent_command_analysis_email_sync(to_email: str, context: dict[str, Any], settings: Any) -> bool:
    subject = f"CloudCare - Agent command analysis: {context.get('status', 'unknown')} ({context.get('run_id', 'latest')})"
    print(f"[Agent Command] Analysis email to {to_email}: {subject}")
    return send_email_sync(to_email, subject, build_agent_command_analysis_email_html(context), settings)


def send_agent_command_analysis_email_status_sync(
    to_email: str, context: dict[str, Any], settings: Any
) -> dict[str, Any]:
    subject = f"CloudCare - Agent command analysis: {context.get('status', 'unknown')} ({context.get('run_id', 'latest')})"
    print(f"[Agent Command] Analysis email to {to_email}: {subject}")
    return send_email_status_sync(to_email, subject, build_agent_command_analysis_email_html(context), settings)
